### ISSUE TITLE
fs2json changes not committed

### ISSUE THREAD

**Issue by ysangkok** [copy/fs2json#1]
When using the fixed libv86 that works with 9p and Linux, I need a new fs2json. The archlinux server doesn't server CORS headers anymore, so I have to make my own image. However, I get the error

```
Uncaught The filesystem JSON format has changed. Please update your fs2json (https://github.com/copy/fs2json) and recreate the filesystem JSON.
```

Thanks in advance.

**Comment by copy** [comment]
Note that the change is only pushed in the built script (`libv86.js`) so far, not in the debug code.
